apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: att-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OptareSolutions/argocd-lab.git
    targetRevision: main
    path: manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
  ignoreDifferences:
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jqPathExpressions: